// setTimeout(() =>{
//     console.log("yoyoyoyo.............")
// },1000)

// // console.log(harsh)

// try{
//     console.log(harsh)
// }
// catch(err){
//     console.log(err)
// }

// setTimeout(() =>{
//     console.log("plaedfc")
// },2000)


// ERROR OBJECT


// try {
    
//     let age =  prompt("enter age");
//     age  = Number.parseInt(age)
    
//     if(age>150){
//         throw new ReferenceError("This is not possible")
//     }
// }
// catch (err){
//     console.log(err.message)
//     console.log(err.name)
// }

// console.log("running")

//FINALY

try{
    let a= 0;
    console.log(prg)
    console.log("Prg ran succ")
}
catch(err){
    console.log("This is error")
    console.log(p)
}

finally{
    console.log("i m good")
}